### PR TITLE
rename value_count to member_count

### PR DESCRIPTION
**Pull request by MovingtoMars**

### CODE REVIEW

**Comment by MovingtoMars** [comment]
I suck at git

**Comment by andrewrk** [comment]
This will accomplish the goal, but we should probably also rename `BuiltinFnIdValueCount` to `BuiltinFnIdMemberCount`.

**Comment by MovingtoMars** [comment]
k, will do right now

**Comment by andrewrk** [comment]
can you squash the two commits into one?

**Comment by MovingtoMars** [comment]
How and why?

**Comment by andrewrk** [comment]
`git rebase -i HEAD~2` - that will open up your editor. then follow the instructions.

Because the first commit was a work in progress. The actual patch that I want to pull is both of them together as one commit.

**Pull request closed without merging**
