### PR TITLE
Somewhat working i386 port

### PR DESCRIPTION
**Pull request by sanxiyn**
These tests fail: enum type sizeof (alignment difference?), 5 more tests which I haven't investigated, and self hosted tests. Other tests pass.

Obviously this can't be merged, but if you have any idea how to handle architecture ports, I am willing to revise this towards that.

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks for the contribution! I do have a few notes which may be of interest in doc/targets.md. 

I went ahead and fixed the sign compares and other GCC 5 incompatibilities. what was `-Wno-error=return-type` for?

I'll start working on cross-compiling and conditional compilation now, and we'll see if we can get this code integrated.

**Comment by andrewrk** [comment]
I just pushed 2bf6c28bc3e535deb651d5b37e332226e0d38930 which adds the ability to cross compile. I was able to build hello_libc.zig both statically and dynamically for windows and run it on a windows box.

Next up, expose the target information via `@compile_var` and then I think we'll be able to integrate your code.

**Comment by andrewrk** [comment]
@sanxiyn I didn't test on a i386 machine yet but I will tomorrow. At any rate the x86_64 tests all pass with this conditional compilation code so it's at least a step toward i386 support. Cheers!

**Comment by sanxiyn** [comment]
Thanks.

**Comment by andrewrk** [comment]
It's not quite working yet due to undefined references which would be resolved by [compiler-rt](http://compiler-rt.llvm.org/)/libgcc.

I'm working on a solution that avoids the cross compiling nightmare.

**Comment by andrewrk** [comment]
Alright, I just tested i386 on ubuntu and it now works out of the box and passes all the tests.

**Pull request closed without merging**
